const MAPS_KEY = 'AIzaSyCbJ6Y_E_zZgyr5kRwYpAAnNSxHtiBnX98';

const ICO_BLUE   = 'AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAACMuAAAjLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD68OUArkQAAL1nKSO8YiCxxnpCyciFVDfDFQAAzKGCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyopgAJkZAAC2XiEytFUTwbVUD/7Ecjf/yHtD18eBTU/DqZgCxY5nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMiNZgD///8AsFkeRa5QD9WuTAj/slIN/8FvNf/FdTv/xnc86sV5QWfFkGkFx4teAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9elAA////AK5aI0+pTA/hqUkI/6tKCP+wUA3/vm0z/8JyOf/DcTX/xHI18sN1PHO9j2kGv4JUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtW9DAFYAAACpWCRMo0kO46NFB/+mRwj/qEkI/61ODf+7ajH/v283/8BuM//BbTD/w24w9MR2PHS9g1kFwHtJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALV1TgCaPwYAo1AePp5FDN6eQgf/oUQH/6NFB/+mRwj/qk0N/7loMP+9bTX/vmsx/79qL//Aaiv/wmor8sFxN2e4wb8Bv31LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAjW8Alz8LAKBSIyqZQg7NmT8H/5xAB/+eQgf/oUQH/6NFB/+oSw3/tmUv/7pqM/+7aS//vGgs/71nKf+/Zib/wGko6sF0O1C/OAAAwa2fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJhIGgCaTCARlkIQrZQ8B/+WPQb/mT8H/5xAB/+eQgf/oUQH/6VJDP+zYy3/t2cy/7hmLv+5ZSr/umQn/7xkJf+9YyL/v2go1L1wNyy+aisAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoaEUAwZiDApJBFIGPOQf9kTkG/5Q7Bv+WPQf/mT8H/5tAB/+eQgf/okcL/7FgK/+0ZTD/tWMs/7ZjKf+4YiX/uWEj/7pgIP+8YB7/vmcnsMF/UA/Ae0kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI9AFQCRQxk+jDkL6Yw2Bv+POAb/kTkG/5Q7Bv+WPQb/mDwE/5k8Av+dQAb/rFkk/7BeKP+xXif/s2Am/7VfJP+2XiH/uF4e/7ldHP+7Xxz6vGkrbdEGAAC5eUoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACbWTcAn2BADoo6ELWGMgX/iTQG/4w2Bv+OOAb/jzYD/5Q9Df+lWTH/uXpZ/8eTdP/QooX/ypRx/716Tf+yYSr/sFke/7NbH/+1Wx3/tloa/7haF/+6YB7bvnVAJr5zOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsoBoAH8tAwCLQRtWgzII9oQxBf+GMwX/iDME/4s1Cf+rakv/2r2u//Xs6P/+/Pz////////////+/v3/+fLu/+jQwP/IjWb/sVsh/7FXGf+zWBj/tVgW/7dZFf+3YCCDZ///ALJvPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIQR4AikUjEIAyDLx/LgX/gS8F/4MvA/+LOhP/xJqH//fy7////////v79//v18v/47uj/+fDq//v28v/+/f3///////z49v/euaH/tWMs/69UFP+yVRT/tFUS/7VZFt23ZSomtmIlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA2EwCGPx5Gey0I9HwsBP9+LQT/hTYP/8iklP/9/Pz////////////16uH/0ppy/8R6Rf/Oj2L/2qmF//Tm2//+/v3////////////jxLD/s14m/65SEf+wUhH/s1QQ/7ZhJG21RwAAtJB2AAAAAAAAAAAAAAAAAAAAAACHRSgAOQAAAHowDoh3KQX/eSoE/3opA/+ygW3//Pr5///////06OD/2rCT/8+Wb/+8azL/wHE5/86QY//LhlX/2aeD/+C1lv/47eb////////////Wqo7/rFAS/65QD/+wUA7/slcXsrFxRAewZzMAAAAAAAAAAAAAAAAAAAAAAIRCJwCFRCoTdisLy3QnBP92JwL/i0Yo/+rd2f///////Pj2/9Gfff+5azb/tmIo/8J7Sv/aro//3raZ/9Sddv/KhFP/0JBh/+fFrf/89/T///////fv6v+8dEb/qkwM/61ODP+vUQ/lsV8lKrBeJAAAAAAAAAAAAAAAAAAAAAAAejUZAHk1GTBxJwjscSUE/3IkAf+1inr////////////9+/n/3bif/8qRav/GhVn/x4db/9Sif//UoHv/2KiG/9Scdf/WoHr/5MCm//z38////////////9mymv+oSw7/qksL/6xODfuxYCdXr1QVAAAAAAAAAAAAAAAAAAAAAABtIwYAcCkNUG0iBPluIwP/dSoK/9S9tP//////+/f1/+fOvf/p0cL/zpp3/8KAU/+/eEj/16mK/922mv/RmXL/1qSA/9utjP/s08H/7dTC//ju6P//////7NnN/6pTG/+nSAn/qUsM/61aInOrTxAAAAAAAAAAAAAAAAAAAAAAAGoiBwBuKA50aiEE/2sgAv95NBf/49XP//nz7//Onn//xYtl/968pf/duaL/y5Ru/7puOv/UpIT/2q6R/8iGWf/YqYj/37aa/+C3m//guJz/3K2M//bo3//17Ob/r2At/6NFB/+mSAn/p00QeqdKCwAAAAAAAAAAAAAAAAAAAAAAZh0DAGUdA3tnHgP/aR4B/3s3HP/p3tn/7t3T/8iUcv/YsZn/7t3S/+TJt//FiGD/unFA/966ov/NlW//xH9R/9CZcv/lxrD/7trL//Tl2v/jvaP/8uHU//jy7v+xZzj/oEIF/6NFB/+hRQd7o0YIAAAAAAAAAAAAAAAAAAAAAABlHgYAaCMMdGUdBP9mHQL/djIY/+TW0f/8+fb/2bWe/+zazv/z6OD/v4BW/61aI/+5cED/37ym/8+ad//Df1H/wntL/8mKX//x4NT/9uri/+fJs//9+vf/9ezn/6teLv+dQAX/oUQI/6JJD3qiRgoAAAAAAAAAAAAAAAAAAAAAAGMdBgBmIgxPYhwE+WQcAv9sJQz/1MC5///////17Ob/1rGZ/9Cjh//MnHz/tm0+/7VqOP/Up4n/16yQ/8OBVf/KkGj/3LSZ/+C7of/WpIH/9OXb///////s29L/oEwb/5tABv+fRAn/pFQgcaFIDwAAAAAAAAAAAAAAAAAAAAAAbS4aAG0uGitiHQfnYRsD/2IaAf+0kIb////////////ky7v/1q+X/+XNvf++f1b/tGo5/9ixl//Pnn7/wH5R/82Xcv/059//7NXG/+G+pv/9+vj//////9e1ov+XPwn/mT4H/5xDCvihVCJNnkoUAAAAAAAAAAAAAAAAAAAAAABvMR8AczcmC2EdCLZfGQL/YBgA/39EM//u5eT///////bt6P/mz8H/4MSx/7dyR/+1bT7/1ayR/7RoNv+7dUb/woFV/966ov/ctpv/793R///////59PL/sHFP/5I5A/+WPQb/mUIM0pdOHxqWTR4AAAAAAAAAAAAAAAAAAAAAAGMiEABeGwYAZCMQZV0ZBP1fGQL/YRoD/66Jgf/+/v7///7+/+nVyP++g17/p1Uh/7NsPv/TqIz/smYz/7pzRP+8dkf/wH1R/9qxlv/79/T//////9Gunf+QOwz/kTkF/5Q8B/+XRhWIlQAAAJZYMgAAAAAAAAAAAAAAAAAAAAAAAAAAAGQlEwBoKhgcXRoHzlwXAv9eGAH/aykX/8qzrv///////v7+//Tq5P/cvKj/uXhO/7VuQv+zaDj/wYNa/+DAq//y5Nr//fz7///////hzMP/l0wn/4o0BP+OOAb/kjwK5JRHGTKUQxMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdDssAFMMAABjIxFWXBkF8lwXAv9dFgD/by8f/8Sqpf/7+fj///////z6+f/t3dL/4se2/+bNvv/v4Nb//Pr4///////+/fz/2sK4/5ZPLv+FMAP/iTQF/404CPuRQhR2kM3sAZBXNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAczkpAHxHOAZfHgyKWxcD+1wXAv9dFwH/ZSEP/51xZ//dzsv/+vf2///////////////////////8+vn/6NrV/7eLev+HOhn/gC0D/4QxBf+HMwb/jD0RqJdYNRCVUy4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbTIhAHE4KA9gHwyXWxcD+VwXAv9eGAH/XhYB/20pGP+NWEv/rYZ7/72clf/BoZj/uJGE/55pVv+EPSL/eSkG/3wsBf9/LgX/gjAG/oc4DrCMRiEbjUMcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXx0LAGkrGg1hIA55XBkG61wXAv9fGQL/YRkB/2EYAP9jGAD/ZhwE/24kC/9wJgn/ciYG/3UpB/94Kgb/eisF/34uCPODOBKTh0UiF4pEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcTcnAHdBMgNlJhU/YB8MrF8bBu5fGgP/YRsD/2QcA/9oHwT/bicL/3EoC/9yKAn/dCgI/3crCfR7MA68fzkXUoBEJgd9PBwA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp4aBAGosGgB3PzALaCkXRmYkEJVkIArQZyMM9GchCP5tJw7+ci0S+HMtENl2MRSieTcZU4JILhKBHgAAhYp9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//w////4D///8Af//+AD///AAf//gAD//wAA//4AAH/8AAA//AAAP/gAAB/4AAAf8AAAD/AAAA/wAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH8AAAD/AAAA/4AAAP+AAAH/wAAD/+AAB//wAA///AA/8=';
const ICO_GREEN  = 'AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAACMuAAAjLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8ABcR0ADPPjSAqzYqrR86YxVzPoTQAvU4AmNa+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgN+0AACxRgAsyoQvHch+vRzIgP48zJH/Rc2W1VLNnEzMz88Bec2sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHjaqwD///8AJcV6QRvEd9IYxXn/Hsd+/zrKjv89ypH/PsuT6UXLlWN1yacEZsuiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABd0ZcA////ACvDeEwbwHHfGcJz/xrEdv8exnv/OciK/zzIjv83yI7/NsmO8D3IkW9rzaYGVsqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT8qKAAClNgArwHNIGr1r4Rm+bf8awHH/GsJ0/x7EeP83xof/OsaK/zbGiv8yx4r/MMeL8z3IkHFmu5kET8GTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAELEewANtVsAJLtpPBi5Y9sZu2f/Gr1r/xq+bv8awHH/HcJ1/zbEhP84xIb/NMWH/zDFh/8txYj/K8aI8TjGjWX/vd8BUb+UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB91aIAErJXACq6Zygatl/LGbdh/xq6Zf8au2j/Gr1r/xq+bv8dwHL/NMKA/zbCg/8yw4P/L8OD/yzDhP8oxIT/KcWG6TvFjk4AvmAAtNHFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+zWgAktF0QHLRbqxm0W/8atl//Grhi/xq6Zf8au2j/Gr1r/x2+b/8ywHz/NMF//zDBf/8uwn//KsKA/yfCgf8jwoH/J8OF0zfBiysrwoYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJv3UAgc+bAhuwVH8YsVX8GrNZ/xq0XP8atl//Grhi/xq6Zf8au2f/Hb1s/zG/ef8yv3v/L797/yzAfP8pwHz/JcF9/yLBfv8fwX//JcKDr0/ClA9IwpEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2tUAAfrlI9Gq5R6BqvU/8asVb/GrNZ/xq0XP8Ztl7/GLdg/xa4Yf8ZumX/K7ty/yy7df8rvHb/Kr14/ye+ef8kvnn/IL96/x2/e/8cwH36KcCDbADgUABKuYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6tWEAQLdmDR2rTLQZrEz/Gq1Q/xqvU/8asVb/F7JW/yG1Xf9CwXb/aM6S/37Xpv+I2K//dNGi/1DHjP8tvXj/Ibtz/yK8dv8fvXf/HL14/xm+eP8dv3zaPcCLJTjAiQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZMOAABOlQAAiqkxVGqlH9hqqSv8arE3/Ga1P/x6vU/9bxYH/teXH/+n47//8/v3////////////9/v7/7vr0/8Dr1v9oz57/JLt0/xy6cv8au3T/GLx1/xa9d/8evHuC/4n/ADq5hQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAip0YAIqdGDxilQLsap0T/GqlH/xiqSf8or1T/kteo//D69P///////f/+//T8+P/t+fT/7Pnz//L7+P/9/v7///////b8+f+k4sT/ML57/xe5b/8XunL/FLtz/xW7dd0kuXsmILl5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6lQQAnqEhGG6Q/9BqlQf8Zp0T/JKtN/6DasP/8/v3////////////j9u3/jdy4/2zSpf9q06b/g9u2/9v16v/9/v7///////////+z583/Kbx3/xS3bf8TuW//Eblx/yG6eW0Au2gAdLKYAAAAAAAAAAAAAAAAAAAAAAAppUMAAJIUABmgOIcZojv/GqM+/xmkP/97y5D/+v37///////h9ev/l966/3XUpf9Yy5b/Y8+f/2rTpf9SzJj/gdq1/5Xhwf/l+PD///////////+R3Lf/FrZq/xK3a/8Qt23/FbdwsjqwfgctsnkAAAAAAAAAAAAAAAAAAAAAAC2mRQAtpkUTHJ83yhqgOP8YoTn/PLBY/93x4f//////9vz5/4HWqv89wX7/Mb53/2nQn/+l48f/ouPF/3TWq/9RzJf/YNGh/6znzv/0/Pj//////+z58v9KxIn/DrRm/w61af8PtmvlILVzKh+1cgAAAAAAAAAAAAAAAAAAAAAAIp84ACGeNy8bnTPsGp41/xifNv+HzZX////////////5/fv/o+DA/2/Qnv9gzJX/dtSm/5fevv+H2rT/hNqz/3TWq/952K//peXJ//P8+P///////////5zfvf8QsmT/DbNl/w61afslt3ZXFLVtAAAAAAAAAAAAAAAAAAAAAAAPlSQAFJcoTxeaLfkanDL/IaE6/7viwv//////9fz4/8Dq0//E69b/e9Sl/1rJkP9nzpz/oeHD/6HixP9w06f/f9ix/4vduf/A7dn/wu3b/+f48f//////z+/e/x+1av8LsWH/DbNl/yG1cXMQs2gAAAAAAAAAAAAAAAAAAAAAABiYKgAcmSxyGpks/xmaL/8spEH/0+zY/+/69P+E1Kj/a8yX/6niw/+l4cL/dNGh/1vKk/+c37//lN67/1fLlv+H2rX/meDB/5rhwv+b4cP/i926/9/27P/n9+7/MLl0/wmuXv8LsGH/EbBlegywYwAAAAAAAAAAAAAAAAAAAAAAGZYnABaVJHkamCn/GZkr/zClRP/c8N//1PDg/3fPnv+d3bn/0/Dg/7roz/9nzJb/XsqU/7Pmzv9006b/TseP/3HTpv+v587/y+/f/9r06f+i48f/1PLm/+758/87vHn/CKxa/wquXv8Hqlx7Ca1eAAAAAAAAAAAAAAAAAAAAAAAYlCQAHJYncRqWJv8Zlyj/LKE9/9Ts1//3/Pn/ot67/9Du3f/h9er/XMeN/yy4bP9eyZL/tufP/3vUqv9Px47/SsaM/17Nmv/U8eT/4vbt/7Lo0P/3/fv/5/bu/zG3b/8Iq1b/C61b/xGsX3oMrV0AAAAAAAAAAAAAAAAAAAAAABCOGAAUkR1MGJMh+BqWJv8imzD/vuHC///////n9u7/ndy4/4vWrP+B06X/Rr99/1fGjf+f37//k9y5/1PIkP9mz53/mN++/6HhxP+B2LH/2/Tp///////S7t3/Hq5e/wmpVP8MrFj/IrBncBCtXAAAAAAAAAAAAAAAAAAAAAAAJZcrACWXKiockyLmGpQk/xmVJP+Qy5T///////////++6ND/m9u2/7/p0f9dx4z/V8WM/6nixv+B1az/T8aM/3HRo//f9er/xe3b/6bjx//4/fv//////6Lcuf8Np1D/CqhS/wyqVvcirGNMFKtbAAAAAAAAAAAAAAAAAAAAAAAomCwAK5kuCRmRHbMakiD/GJMh/0SnS//k8uX//////+n37//D6dT/tOTJ/07BgP9axo3/o9/B/z2+ff9DwYP/U8eP/6Lgwv+b37//0PDh///////w+fP/T7t5/wekSf8Kp07/DahT0B+nXhgep10AAAAAAAAAAAAAAAAAAAAAAA6JDwAakR0AHpIgYRqRHvwakiD/GpMj/4jGjP/9/v3//v/+/8rs2P9kx47/KrNl/1rFjP+f3b3/Orx7/0LAgf9FwoT/T8WM/5Xcu//0+/j//////5rWr/8Pokj/CqNJ/wqlTP8Xp1aFAIwAADupbAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+SHwAjlCMZGI4ZyRqRHf8Zkh//Kpox/6/Ysf///////v/+/+X17P+s4cL/aMqV/2DHkf9AvX3/WcaQ/6rjx//a8+f/+/78//////+/5Mr/KKhU/wieQv8KoUb/DaNL4R6mWC8XpVMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP6A+AA2JDgAfkR9RGY8a8BqRHf8YkR7/MJs2/6XTqP/3+/f///////n9+//Z8uT/wunV/8Lq1f/W8eP/+P36///////7/fv/st29/y6nU/8Imzv/Cp1A/wygRfoaolBx/7H/ADejYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP6E/AFOrUwUbjxuCGI8Z+hqRHv8YkR//I5Yp/224cv/H5Mn/8/r0///////////////////////2+/f/z+nU/3TBhf8bnD7/CZg2/wqaOv8LnD3+F6BJo0WqbA88qGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANZw1ADqeOg0ckByPGI4Z9xqRHf8ZkiD/GJIg/ymaMf9Trlr/fcKD/5XOm/+TzJv/fMGH/1GuYf8jmjz/C5Mt/wqVMf8KlzT/Cpk3/RaeQ6s0pVwZKqVVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHZAdADWcNQohkiFxGI8a5hiQHP8akiD/GZQj/xeUI/8XlSX/GJYo/xOQJf8PjyX/DZAo/w2RK/8Mky3/CpQu/wyWM/Aam0GLNqFYFCygUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR6RHAGu1agIrlys4HpIfoxmQHeoYkR7+GJMi/xmVJv8Zlyj/FZAm/xGPJv8PkCb/DZEo/w6SLPEVljW1JJpESkeeYQY9nVgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AD+hQABcr1wIMZszPCWWKYoelSXGHZYn7BuWKPoakSj8G5Et8hmSLdAglTaZKphCS0+jYg4tnUcAb6J5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//w////4D///8Af//+AD///AAf//gAD//wAA//4AAH/8AAA//AAAP/gAAB/4AAAf8AAAD/AAAA/wAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH8AAAD/AAAA/4AAAf+AAAH/wAAD/+AAB//wAA///AA/8=';
const ICO_YELLOW = 'AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAACMuAAAjLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAM//ACnX/yEY1/+wONz7y0/b8zgA//8AadPnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS9j/AAC//wAh0f8xDc//vwbR//4v2///PN7810fc9k9qx9kCU9PrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF/a/wD///8AH8v/QQnJ/9QAyv//Bc7//y3Y//803P//NN396j3b92Viz+MFVdTqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABZ1P8A////ACDH/00IxP/gAMT//wDH//8Fy///K9X//zLZ//8u2///Ltz98Tjb+HBi1OoHTtfxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdtn/AACc/wAhwv9JCL7/4gC///8Awv//AMT//wXI//8q0///MNb//yzY//8o2v//KNv+9DXZ93R3xtUEVNDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAErI/wAAtf8AH73/Owi4/9oAuf//ALz//wC///8Awf//BcX//yjQ//8u1P//KtX//yfX//8j2f//JNr98THY92bqqaUBVszkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqzv8AGLb/AC+9/ycMtf/KALT//wC2//8Auf//ALz//wC///8Ew///J83//yzR//8o0v//JdT//yLW//8e2P//Itn96DjY9E8A5/8Ao8fRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC24/wA4u/8OD7D/qQGu//8Asf//ALP//wC2//8Auf//ALz//wTA//8ly///K87//yfQ//8j0f//INP//x3V//8Z1///Itn71D3V7you2PYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHvP8Apdj/Ahat/3oDqf/7AKv//wCu//8Asf//ALT//wC2//8Auf//BL3//yTI//8pzP//Jc3//yLP//8e0P//G9L//xjU//8W1///Idj5rkTU7g881fEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABiq/wAlrv86B6X/5wCl//8AqP//AKv//wCu//8Asf//ALP//wC1//8DuP//HsP//yLI//8gyf//IMz//x3O//8az///F9H//xPU//8U1v76K9X1agDr/wBizuQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8sv8ASrf/DRKk/7EBoP//AKP//wCl//8AqP//AKn//wiu//8svP//V8v//3LW//+C3f//bdn//0jR//8kyv//F8r//xjM//8Vzv//EtH//w/T//8X1PvZOdLwJTLT8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AAOa/wAipv9RBZz/9gCd//8AoP//AKL//wWl//9Fvf//q+L//+f3///8/v/////////////9/v//7vv//73v//9g2f//G8r//xLL//8Rzv//Ds///w3S/v8f0/d+AP//AFbM5QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8rP8ASrH/DA+b/7UAl///AJr//wCc//8Oo///gM///+75/////////f////H8///n+///6vv///L9///9//////////b9//+f6P//Jc3//w3K//8NzP//Cs///xHR+9oxz/AjKs/yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByc/wAro/9BB5T/8QCU//8Al///CZz//4zR///7/f/////////////h+f//beL//0Da//9f4f//gOj//9r5///9//////////7///+t6///Hsv//wrJ//8JzP//Cc7+/iPO9WoA0P8Ar8/YAAAAAAAAAAAAAAAAAAAAAABnuf8AAF//ABiX/4ACj///AJL//wCT//9mvv//9/v////////f+P//kOb//2rf//8t1P//Ndb//2Dh//9P3///fuj//5Ls///l+/////////7///+K4///C8f//wjJ//8Gy///Fs35rm/M3gZKzOoAAAAAAAAAAAAAAAAAAAAAAEOn/wBMq/8PDpD/wwCM//8Ajv//HZz//8/q////////9v3//3jg//8w0P//Ic7//0TX//+M5///mer//3Hk//9M3v//W+L//6rw///z/f///////+b5//87z///BMX//wTI//8Ly/ziL8vxJy3L8gAAAAAAAAAAAAAAAAAAAAAAMp3/ADGc/ywKi//oAIn//wCK//9qu////f7////////5/v//nOf//2Xb//9U2P//Vtr//37j//985P//geb//3Dk//915f//ou////P9/////////////5Hk//8Fw///A8X//wbI/vopyvRUEsn5AAAAAAAAAAAAAAAAAAAAAAALh/8AGY7/QwOF//YAhv//B4z//7Hb////////9fz//7vu///A7///ct3//07W//9C1P//h+T//5rp//9t4f//fOX//4jo//++8///wPT//+f7////////0PP//xfE//8Bwv//BMX+/yPH9XELx/wAAAAAAAAAAAAAAAAAAAAAAAyF/wAnkv9pBIL//wCD//8UkP//0On//+77//973P//Ydb//6Pn//+f5///atv//zTQ//+B4v//j+b//1Pb//+E5v//lur//5fr//+Y7P//h+r//975///n+P//Kcf//wC///8Cwv7/E8T5eQbD/QAAAAAAAAAAAAAAAAAAAAAACoH/AB+M/3UDf///AID//xmP///Y7P//0fP//27X//+W4///0PP//7Xs//9b1v//OtD//6Dp//9t3v//Stf//23g//+t7v//yvT//9n4//+f7v//0/f//+36//8yx///ALz//wG///8Mwvx6BMH+AAAAAAAAAAAAAAAAAAAAAAALf/8AJIz/aQN9//8Aff//Fov//9Lp///2/f//m+P//83x///f9///UdL//xzG//86zv//pOn//3Xf//9L1v//Rdf//1nc///S9v//4fn//7Dw///3/v//5/j//yvD//8AuP//Arz+/xK/+nkGvv0AAAAAAAAAAAAAAAAAAAAAAA1+/wAZhP9CA3r/9gB6//8Kgv//udv////////l+P//luH//4Td//942///OMv//zPL//+G4f//juT//0/W//9j3P//lej//57q//995P//2vj////////W8v//Gbr//wC2//8Duf7/I772bgu8/AAAAAAAAAAAAAAAAAAAAAAAM5D/ADOQ/yYKe//jAHj//wB5//93t/////////////+56///lOH//7vs//9R0f//NMr//5Xk//983v//S9T//23d///e+P//xPL//6Ps///4/v///////5zf//8Dsf//ALP//wW3/fYlu/NJFbr3AAAAAAAAAAAAAAAAAAAAAAA6k/8AUZ//Bw16/60Adf//AHf//yeN///c7P///////+f4//+/7P//r+j//0HL//84yv//j+L//zPL//9A0P//T9X//5/o//+Y6P//z/T////////v+f//RcD//wCt//8Asf//CbX7zSy57hYquO8AAAAAAAAAAAAAAAAAAAAAAP///wAJdv8AG4D/XAN0//sAdf//AHf//3q3///8/v///v///8fu//9a0P//G7///znI//+L4P//Mcn//z7O//9B0f//S9T//5Lm///0/P///////5vb//8Gqf//AKv//wGu/v8WsvaDAJD/AE644wAAAAAAAAAAAAAAAAAAAAAAAAAAACOD/wAphv8XCXX/xgBy//8Adf//EX7//6XO/////////v///+P3//+m5f//Scz//z7K//82yf//VtP//6jp///Z9v//+v7////////A5v//Ia3//wCl//8AqP//B6z74SCx8S4YsPUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa6v/AABj/wAZff9QBHL/8QBy//8AdP//GoL//57K///4+/////////j9///R8v//ter//73t///V9P//+P3////////9/v//tuH//yqr//8An///AKP//wOm/vsUqvVy//8AADur4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMov/AEqY/wYPd/+DAnH/+gBy//8AdP//DXv//2Sq///I4f//9vr////////////////////////5/P//1Oz//3fD//8Xnv//AJn//wCd//8BoP7/D6X4pjCp5xApqOoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ4X/AC6J/w4Od/+SAnH/+ABy//8Adf//AHX//xSB//9Inf//err//5TH//+Xy///g8T//1Wv//8fmf//ApH//wCV//8Al///Apv+/Quf+K8foOobFJ/vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFHr/AC2J/woReP91BXP/6QBz//8Adf//AHf//wB4//8Ae///AX7//wiF//8FiP//Aor//wON//8CkP//AZL//wOW/fIPmvaRJ57nFiCh8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOY//AFKc/wMYff88C3f/qgR1/+0Bdv//AHj//wB7//8Bfv//CIX//wiH//8Fif//BIv//wWP/fQKkvm8FJXwUTCV2Qcgl+oA/4EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzt7/ABF6/wAyi/8LFn7/RA97/5MIev/PCX3/8wV+//4Lg/7+D4j7+A2J+toRjPaiF47xUyWQ5RIRkv0AOZC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//w////4D///8Af//+AD///AAf//gAD//wAA//4AAH/8AAA//AAAP/gAAB/4AAAf8AAAD/AAAA/wAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH8AAAD/AAAA/4AAAf+AAAH/wAAD/+AAB//wAA///AA/8=';
const ICO_RED    = 'AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAACMuAAAjLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AODD8AFpU/R9KQv2sYlv7x3hy9TQAAP8AkY3lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAenX7AAAA+QBRS/svPDT7vTYu/P5YUP7/ZF381W9p9kylo9oCgX3sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAImF+gD///8AS0T4PzUu+dIuJvr/Myv7/1RO/f9bVP7/Xlf96Whh92KIhOYFfHfsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGgvkAAAC6AElD9ksxKvbeKyP3/ywk+P8yKvr/Ukz8/1lS/f9XT/7/WFH98GJb926OiuAGeHPrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoJ36AAAA7ABFP/NHLijz4Cgh9P8pIvb/KyP3/zAo+f9QSfv/VlD8/1RN/f9SS/7/VEz9819Y9nKYk9kEeHLpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGtn8wAkHvAAQDvxOisl8NglHvH/JiDz/ygh9P8pIvb/Lyf3/05H+f9UTfv/Ukv8/1BJ/f9OR/7/UEn98FxV92T//6IBenfqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEgvQAOTPuAE1J8CctJ+7JIhzv/yQd8P8lH/H/JyDz/ygh9P8tJvb/S0X4/1FK+f9PSPv/TUb8/0xF/f9KQv7/Tkf86F9Z804QBP8AsbHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEtH7QBUUe4OLSnsqCAb7P8hG+3/Ihzv/yQd8P8lH/H/Jh/z/ysl9P9JQvf/Tkj4/0xG+f9KRPv/SUL8/0hA/f9GPv7/Tkb702Re8CpZUfYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaVu0ArazzAjAs6nofGun7Hhjq/x8a7P8hG+3/Ihzv/yQd8P8lHvH/KiPz/0ZA9v9MRvf/SkP4/0hB+f9HP/v/RT78/0Q8/f9EO/7/TUX5rmhi6A9hXOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4q6AA7N+k6IBzn5xsW5/8dGOn/Hhnq/x8a7P8hG+3/IBnu/x8Y7/8jHPH/Pzn0/0U/9v9EPvb/RT/4/0Q9+f9DPPv/QTr8/0A4/f9COvz6VE31aQAA/wB9eeMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOS+kAWljqDSck5rEZFOX/GhXm/xsW6P8cF+n/GhXq/yEc7P9APPD/ZmL0/4J+9/+TkPj/g3/4/2Rf9/9GQPf/Pjf4/0A5+f8/OPv/Pjb7/z01/P9EPPvZX1nwJVlS8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////ABgV4gAzMOVSGhbj9hcT5P8YFOX/GRTm/xsW6P9UUe7/sa/4/+jo/f/8/P/////////////9/f//8fD+/8fF/P95dPr/QDr4/zsz+f87NPr/OjP7/zsz/P9JQfZ/AAD/AHFs6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJRuYAVlPnDCEd4bUUEeH/FhLi/xUR4/8gHeb/iYfy/+/v/f///////v7///Tz///s6///7+7///X0///9/f////////f3//+uq/z/SEL5/zcw+f84MPr/Ny/7/z42+ttWUO8kUUrxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACon4QA4NeNBFxTf8hIP3/8UEOH/Ghfj/5OS8v/7+//////////////m5f//iIT9/2Zg/f+BfP7/mZX+/+Hg///9/f////////////+5tvz/Qjz4/zQt+f81Lfr/Ni76/kpD9GokHP8Asa7MAAAAAAAAAAAAAAAAAAAAAABqaegAAADOACUi34ARD93/EQ7e/xAN3/9vbez/9/f+///////k4/7/o6D9/4WA/P9STPz/XFX8/4F8/v9xa/7/mJP+/6ml///q6f////////7+//+dmvv/Myz4/zIr+P8yKvr/Pzf2r4B83gZlYOgAAAAAAAAAAAAAAAAAAAAAAEtJ4wBTUuQPGhjcww4M2/8OC9z/Kifh/9LS+f//////9/f//5CL+/9UTfr/SUL6/2Vf+/+kof3/r6z+/4yI/v9wav7/fXf+/7y5///29f///////+rp/v9ZU/j/Lib3/y8o+P81LvjjUErvJ05I7wAAAAAAAAAAAAAAAAAAAAAAOjjfADk33ywVE9roDQra/wsI2/9xcOr//f3////////6+v//rar8/4B7+/9ybfv/c277/5iU/f+YlP3/mZX9/4yI/v+RjP7/tbL///X1/////////////6Kf+/8tJvX/LSb3/zEp9/pNRvBUOzP1AAAAAAAAAAAAAAAAAAAAAAATEtgAIB/aQw0L1/YLCdj/ExHb/7W09P//////9vb//8bE/f/KyP3/iob7/2xn+v9jXfr/n5v8/6+s/f+IhP3/lZH+/6Cc/v/Lyf//zcv//+zr////////19b9/zo09f8qI/X/Lif2/0dA8HE0LfYAAAAAAAAAAAAAAAAAAAAAABMR1wAsK9tpDArW/wkH1/8fHdv/0tL4//Hw//+QjPn/enb5/7Kv/P+vrPz/g3/6/1dR+f+YlPz/paL9/3Nu/P+bmP3/q6f+/6yo/v+tqf7/oJz+/+Xk///q6v7/SUT1/ycg9P8rJPX/OTLyeS8o9QAAAAAAAAAAAAAAAAAAAAAAEA/VACUk2XUKCdX/BwbV/yIh2//a2fn/2df9/4WB+f+mpPv/2Nf9/8G//P92cvn/W1X5/7Ow/P+Khfz/bGb7/4mF/P+9uv7/1NL+/+Hf//+zsP7/3Nv//+/v/v9PSvT/JR7z/yki9P8yLPN6LCX0AAAAAAAAAAAAAAAAAAAAAAAQD9QAKSnZaQkI0/8GBdT/HRzZ/9PS+P/49///qqj6/9XT/f/k4/7/bWj4/0E79/9aVPj/tbL8/4+L+/9sZvv/aGL7/3l0/P/b2v7/5+b//8C9/v/5+P//6un9/0dC8v8jHPH/KCHy/zcw8HksJfIAAAAAAAAAAAAAAAAAAAAAABER0wAdHdZBCAfS9gUE0/8PDtX/ubjz///////p6f7/pqP6/5eT+f+Nivn/WFL3/1RO+P+cmPv/o6D8/29q+v9/evv/qab9/7Gu/f+Xk/3/4uD////////Z2Pz/NS/w/yIc8P8oIfH/Qz3rbi8o8AAAAAAAAAAAAAAAAAAAAAAAODjaADg42iYODdLiBAPR/wMC0v92duf////////////Ewvz/pKH6/8XD/P9taPj/VE/3/6il+/+Ukfv/a2b5/4iD+//k4/7/z83+/7Wy/f/5+f///////6Si9/8iHO3/Ihzv/ygi7/ZFQOpINzHsAAAAAAAAAAAAAAAAAAAAAABERNsAYmLhBxEQ0qsDA9D/AgLR/ygo2P/a2vj//////+vq/v/Jx/z/u7n7/19Z9/9YUvf/pKH7/1pU+P9hXPn/b2r6/7Gu/P+rqPz/2Nf+///////u7f3/U0/v/x0X6/8hG+3/KyXtzE5K5BZLRuQAAAAAAAAAAAAAAAAAAAAAAAAAAAAODtEAICDUWgYF0PoDAtD/AwLR/3Z15v/7+/7//v7//8/N/P9ybvf/PTf0/1dR9v+gnPr/V1L3/2Ba+f9jXfn/a2b5/6aj/P/29v///////56c9f8fGun/Hhjq/yEb7P81MemBAAD/AG9s3QAAAAAAAAAAAAAAAAAAAAAAAAAAAC4u1gA1NNcWDQ3QwwIBz/8CAdD/ERDT/6Cg7f/+/v///v7//+fm/v+zsfv/ZWD2/15Z9v9aVff/c275/7i1/P/g3/7/+/v///////++vvj/MCzo/xoV5/8cF+n/JiHp30I+5Cw6NecAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjY3oAAAAygAiItRMBwfP7wEBz/8BAdD/GBjU/5aW7P/29v3///////n5///Y1/3/wb/8/8rI/P/c2/3/+fn////////7+///srH1/zQx5/8WEuX/GRXm/x4a6Ps0L+RwAAD/AGBc2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASEjbAG5u4wUXF9J+BATO+QEBz/8BAdD/DAvS/1xc4f/AwPP/8vL9///////////////////////29v7/zc34/3Nx7P8iH+L/FBDi/xcT5P8aFuX+LSnkolVT2w9MSd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOjrYAERE2gwWFtGMBQXO9wEBz/8CAtD/AQHR/xMS1P9BQd3/cG/m/4yL6/+Rke3/e3rq/1FQ5f8kIt//EQ7e/xMQ3/8UEeH/GBTj/Cck46pGQ9sYNjPhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMjLXAEVF2ggcHNJvCQnP5QICz/8DAtD/AwPR/wIB0v8CAdP/BgXV/w8N2P8ODdn/Dw3a/xEP3P8SD93/Eg/f/xkW4PAqJ9+LTkvXE0A93AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZWXhAKen7gIqKtU3FRTSowoJ0OoFBND+BQTS/wUE0/8IB9T/EA/X/xEQ2P8RD9r/Eg/b/xYT3PEhHty1MzDaSmJgzgVVU9IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AD082QBVVd4ILCzWPB4d1IoUE9PGFBPU7RMS1fsYF9f8Hh3Y8x0c2NEnJdiZMzLWS1FQzg8tK94Ah4muAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//w////4D///8Af//+AD///AAf//gAD//wAA//4AAH/8AAA//AAAP/gAAB/4AAAf8AAAD/AAAA/wAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH8AAAD/AAAA/4AAAf+AAAH/wAAD/+AAB//wAA///AA/8=';

interface MapProject {
  id: string;
  title: string;
  category: string;
  status: string;
  club: { name: string; clubCode: string };
  location: { coordinates: [number, number]; address?: string; placeName?: string };
}

export function buildProjectMapHTML(
  projects: MapProject[],
  statusColors: Record<string, string>,
  primaryColor: string,
): string {
  const markerData = projects.map((p) => ({
    id: p.id,
    lat: p.location.coordinates[1],
    lng: p.location.coordinates[0],
    color: statusColors[p.status] || primaryColor,
    status: p.status,
    title: p.title.replace(/'/g, "\\'"),
    club: (p.club?.name || '').replace(/'/g, "\\'"),
    category: p.category,
    placeName: (p.location.placeName || '').replace(/'/g, "\\'"),
  }));

  return `<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body, #map { width: 100%; height: 100%; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script src="https://maps.googleapis.com/maps/api/js?key=${MAPS_KEY}"></script>
  <script>
    var ICONS = {
      upcoming:  'data:image/x-icon;base64,${ICO_BLUE}',
      ongoing:   'data:image/x-icon;base64,${ICO_YELLOW}',
      completed: 'data:image/x-icon;base64,${ICO_GREEN}',
      _default:  'data:image/x-icon;base64,${ICO_RED}',
    };

    var map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: 7.8731, lng: 80.7718 },
      zoom: 7,
      mapTypeControl: false,
      streetViewControl: false,
      fullscreenControl: false,
    });

    map.addListener('click', function() {
      window.ReactNativeWebView.postMessage(JSON.stringify({ id: null }));
    });

    function pinIcon(color, status) {
      var iconUrl = ICONS[status] || ICONS._default;
      return {
        url: iconUrl,
        scaledSize: new google.maps.Size(32, 32),
        anchor: new google.maps.Point(16, 32),
      };
    }

    var markers = ${JSON.stringify(markerData)};
    markers.forEach(function(m, i) {
      setTimeout(function() {
        var marker = new google.maps.Marker({
          position: { lat: m.lat, lng: m.lng },
          map: map,
          icon: pinIcon(m.color, m.status),
          title: m.title,
          animation: google.maps.Animation.DROP,
        });
        marker.addListener('click', function() {
          window.ReactNativeWebView.postMessage(JSON.stringify({
            id: m.id, title: m.title, club: m.club,
            category: m.category, status: m.status,
            placeName: m.placeName, lat: m.lat, lng: m.lng,
          }));
        });
      }, i * 40);
    });
  </script>
</body>
</html>`;
}

export function buildLocationPickerHTML(
  initialLat: number | null,
  initialLng: number | null,
): string {
  const hasInitial = initialLat !== null && initialLng !== null;
  const centerLat = hasInitial ? initialLat : 7.8731;
  const centerLng = hasInitial ? initialLng : 80.7718;
  const zoom = hasInitial ? 14 : 7;

  return `<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body, #map { width: 100%; height: 100%; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script src="https://maps.googleapis.com/maps/api/js?key=${MAPS_KEY}"></script>
  <script>
    var ICON_URL = 'data:image/x-icon;base64,${ICO_BLUE}';

    var map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: ${centerLat}, lng: ${centerLng} },
      zoom: ${zoom},
      mapTypeControl: false,
      streetViewControl: false,
      fullscreenControl: false,
    });

    var marker = null;

    function pinIcon() {
      return {
        url: ICON_URL,
        scaledSize: new google.maps.Size(32, 32),
        anchor: new google.maps.Point(16, 32),
      };
    }

    function attachDrag(m) {
      m.addListener('dragend', function() {
        var pos = m.getPosition();
        window.ReactNativeWebView.postMessage(JSON.stringify({ lat: pos.lat(), lng: pos.lng() }));
      });
    }

    ${hasInitial ? `
    marker = new google.maps.Marker({
      position: { lat: ${initialLat}, lng: ${initialLng} },
      map: map,
      draggable: true,
      icon: pinIcon(),
      animation: google.maps.Animation.DROP,
    });
    attachDrag(marker);
    ` : ''}

    map.addListener('click', function(e) {
      var lat = e.latLng.lat();
      var lng = e.latLng.lng();
      if (marker) {
        marker.setPosition(e.latLng);
      } else {
        marker = new google.maps.Marker({ position: e.latLng, map: map, draggable: true, icon: pinIcon(), animation: google.maps.Animation.DROP });
        attachDrag(marker);
      }
      window.ReactNativeWebView.postMessage(JSON.stringify({ lat: lat, lng: lng }));
    });
  </script>
</body>
</html>`;
}

export { MAPS_KEY };
